version: '3.8'
services:

  vs_pod:
    container_name: vs_pod
    restart: always
    volumes:
      - ./video:/usr/src/app/video
    build:
      context: ./
    env_file:
      - .env
    ports:
      - 8001:8001

volumes:
  video: